
#index:
  # path: /
  #  controller: App\Controller\DefaultController::index


generate_pdf:
    path: /subscription/plan/{id}/generate-pdf
    controller: App\Controller\ChooseSubscriptionController::generatePdf
    methods: GET


app_payment_process:
    path: /payment/process
    controller: App\Controller\PaymentController::process
    methods: [POST]
=======
Lecon:
    path: /Lecon
    controller: 'App\Controller\LeconController::index'
Categorie:
    path: /Categorie
    controller: 'App\Controller\CategorieController::index'

    #index:
#    path: /
#    controller: App\Controller\DefaultController::index

Evenement:
  path: /Evenement
  controller: 'App\Controller\EvenementController::index'

Sponsor:
  path: /Sponsor
  controller: 'App\Controller\SponsorController::index'

app_t_t_t:
  path: /t
  controller: 'App\Controller\TTTController::index'

app back:
  path: /back
  controller: 'App\Controller\TTTController::index'

generate_pdf:
  path: /evenement/plan/{id}/generate-pdf
  controller: App\Controller\EvenementController::generatePdf
  methods: GET
