Lecon:
    path: /Lecon
    controller: 'App\Controller\LeconController::index'
Categorie:
    path: /Categorie
    controller: 'App\Controller\CategorieController::index'

    #index:
#    path: /
#    controller: App\Controller\DefaultController::index
